# @package _global_

data:
  train_files: ${oc.env:HOME}/data/gsm8k/train.parquet
  val_files: ${oc.env:HOME}/data/gsm8k/test.parquet
  max_response_length: 1024
  filter_overlong_prompts: true

# actor_rollout_ref:
#   rollout: 
#     val_kwargs:
#       # sampling parameters for validation
#       top_k: -1 # 0 for hf rollout, -1 for vllm rollout
#       top_p: 0.5
#       temperature: 0.8
#       n:1